### ISSUE TITLE
[BUG] TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by MikkelDK** [Triniayo/nodejs-discord-csgoupdate#2]
Hi,

How to fix error?
```
0|csgo     | TypeError: Cannot read property 'includes' of undefined
0|csgo     |     at /home/mikkel/bots/csgobot/app.js:87:24
0|csgo     |     at <anonymous>
0|csgo     |     at process._tickCallback (internal/process/next_tick.js:189:7)
```

```bash
(node:24488) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'includes' of undefined
    at /root/test/app.js:87:24
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:24488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:24488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by MikkelDK** [comment]
@Triniayo are you still active? ;) how to fix this error.

**Comment by Triniayo** [comment]
Hey, yes I am.

Might be that they've changed something on their site. I'll take a look at it soon.

**Comment by MikkelDK** [comment]
@Triniayo let me know, once you are updating! ;) your script is nice to use. but since there are "issues", so I can't use it! :-(

**Comment by MikkelDK** [comment]
@Triniayo Any update??

**Comment by MikkelDK** [comment]
It seems this will not be updated! =)
